### ISSUE TITLE
Unable to run ws, argv.misc.config undefined?

### ISSUE THREAD

**Issue by roowilliams** [75lb/local-web-server#17]
Running on Ubuntu 15.04. Any ideas?

```
roo@roo-laptop:~/Development/react/one$ ws
/usr/local/lib/node_modules/local-web-server/bin/ws.js:70
if (argv.misc.config){
             ^
TypeError: Cannot read property 'config' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/local-web-server/bin/ws.js:70:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by 75lb** [comment]
damn, sorry about that.. was caused by a dodgy dependency.. please update (to version 0.5.21) and try again..

**Comment by roowilliams** [comment]
Thanks! Your update fixed it :)
