### ISSUE TITLE
Can't start server with `--log-format none`

### ISSUE THREAD

**Issue by adambiggs** [75lb/local-web-server#18]
Starting with `v0.5.20`, it's not possible to disable console logging.

```
$ ws --log-format none

/Users/adam/.nvm/versions/node/v0.12.4/lib/node_modules/local-web-server/node_modules/connect/index.js:87
  if (typeof handle.handle === 'function') {
                   ^
TypeError: Cannot read property 'handle' of undefined
    at Function.use (/Users/adam/.nvm/versions/node/v0.12.4/lib/node_modules/local-web-server/node_modules/connect/index.js:87:20)
    at launchServer (/Users/adam/.nvm/versions/node/v0.12.4/lib/node_modules/local-web-server/bin/ws.js:113:9)
    at Object.<anonymous> (/Users/adam/.nvm/versions/node/v0.12.4/lib/node_modules/local-web-server/bin/ws.js:88:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

All other logging modes seem to work fine.

**Comment by 75lb** [comment]
Fixed and released, thanks for the report

**Comment by adambiggs** [comment]
That was fast! :beers:

**Comment by 75lb** [comment]
it would have been done quicker if i had a reliable wifi connection atm! tbh it was a simple fix.. i have a couple of new features to add when i get time - proxying and user-defined routes..
